// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_HUtq13_ED64UHZesB-6B-hjS-MVqLvo',
    appId: '1:64500882300:web:2d497d120644825549e2f9',
    messagingSenderId: '64500882300',
    projectId: 'diploma-37e65',
    authDomain: 'diploma-37e65.firebaseapp.com',
    storageBucket: 'diploma-37e65.firebasestorage.app',
    measurementId: 'G-RFC1NTF6HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bp08K3c1EalApkjZHvng0seJkT63k4c',
    appId: '1:64500882300:android:efbd1e3093ebb0de49e2f9',
    messagingSenderId: '64500882300',
    projectId: 'diploma-37e65',
    storageBucket: 'diploma-37e65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFVBrk1RUIo88YOt-fCxNyeAuI8IUOZok',
    appId: '1:64500882300:ios:46a48dedfe55422b49e2f9',
    messagingSenderId: '64500882300',
    projectId: 'diploma-37e65',
    storageBucket: 'diploma-37e65.firebasestorage.app',
    iosBundleId: 'com.example.foodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFVBrk1RUIo88YOt-fCxNyeAuI8IUOZok',
    appId: '1:64500882300:ios:46a48dedfe55422b49e2f9',
    messagingSenderId: '64500882300',
    projectId: 'diploma-37e65',
    storageBucket: 'diploma-37e65.firebasestorage.app',
    iosBundleId: 'com.example.foodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_HUtq13_ED64UHZesB-6B-hjS-MVqLvo',
    appId: '1:64500882300:web:b994e06f7494ba1b49e2f9',
    messagingSenderId: '64500882300',
    projectId: 'diploma-37e65',
    authDomain: 'diploma-37e65.firebaseapp.com',
    storageBucket: 'diploma-37e65.firebasestorage.app',
    measurementId: 'G-J7L1VJ1KVJ',
  );
}
